Repository actualbudget/docs, pull requests merged in 2022-10, with the labels that each got.

#21 Installation Overview
  docs/Installing/overview.md
  sidebars.js
Labels: documentation

#32 Local Install Docs
  docs/Installing/Local/your-own-machine.md
  sidebars.js
Labels: documentation, complete

#35 ActualQL Examples
  docs/Developers/ActualQL/Examples.md
  docs/Developers/ActualQL/Functions.md
  docs/Developers/ActualQL/Overview.md
  docs/Developers/Building-Windows.md
  sidebars.js
Labels: documentation, waiting-review, complete

#33 2210DD Release Notes
  docs/Release-Notes/22.10.25.md
  sidebars.js
Labels: documentation, complete

#42 Filtering In Actual
  docs/Budgeting/filters.md
  sidebars.js
  static/img/accounts.png
  static/img/filtering/accounts.png
  static/img/filtering/conditions-1.png
  static/img/filtering/conditions-2.png
  static/img/filtering/conditions-3.png
  static/img/filtering/filter.png
  static/img/filtering/highlight-2.png
  static/img/filtering/highlight.png
  static/img/filtering/multiple-filters.png
Labels: documentation, complete

#48 Add simple sync migration steps
  docs/Getting-Started/migration/migration-intro.md
  docs/Getting-Started/migration/simple-sync.md
  sidebars.js
Labels: documentation, enhancement, complete
