Repository actualbudget/docs, pull requests merged in 2023-07, with the labels that each got.

#220 Update the restore doc
  docs/backup-restore/restore.md
Labels: ✅ Approved

#219 Add redirects for all pages on the old actualbudget.com
  static/_redirects
Labels: ✅ Approved

#221 Entry for available funds percent goal
  docs/experimental/goal-templates.md
Labels: 🔍 Ready for Review, ✅ Approved

#181 check template blurb
  docs/experimental/goal-templates.md
  static/img/goal-template/goal-template-2.png
Labels: 🔍 Ready for Review

#223 [WIP] :bookmark: (23.7.0) Nordigen release, stability improvements
  blog/2023-07-04-release-23.7.0.md
  docs/releases.md
Labels: 🚧 WIP

#224 Add warning not to install 23.7.0
  blog/2023-07-04-release-23.7.0.md
  docs/releases.md
Labels: ✅ Approved

#225 :bookmark: (23.7.1) critical sync fixes
  blog/2023-07-04-release-23.7.0.md
  blog/2023-07-05-release-23.7.1.md
  docs/releases.md
Labels: ✅ Approved

#227 Add more documentation for 'up to' keywords and spelling issues
  docs/experimental/goal-templates.md
Labels: ✅ Approved

#226 instructions on manual db updates
  docs/backup-restore/restore.md
Labels: ✅ Approved

#229 Spelling corrections
  README.md
  blog/2023-01-12-release-23.1.12.md
  blog/2023-02-05-release-23.2.5.md
  blog/2023-05-04-release-23.5.0.md
  blog/2023-07-04-release-23.7.0.md
  blog/welcome.md
  docs/advanced/bank-sync.md
  docs/contributing/index.md
  docs/contributing/releasing.md
  docs/getting-started/sync.md
  docs/releases.md
Labels: ✅ Approved

#230 :bookmark: (23.7.2) more patches (not so critical, but still annoying)
  blog/2023-07-09-release-23.7.2.md
  docs/releases.md
Labels: ✅ Approved

#231 Change and Add Create Accounts Images
  docs/accounts/index.md
  static/img/add-account/CreateAccount.png
  static/img/add-account/CreateAccount1.png
  static/img/add-account/CreateAccount@2x.png
Labels: ✅ Approved

#235 New Account - Add link to Bank Sync Notes
  docs/accounts/index.md
Labels: ✅ Approved

#232 added section for saving filtered transactions for 23.7.1 update
  docs/budgeting/filters.md
  static/img/filtering/filter.png
  static/img/filtering/modify-saved.png
  static/img/filtering/save-filter.png
  static/img/filtering/select-saved-1.png
  static/img/filtering/select-saved-2.png
  static/img/filtering/set-filter-name.png
Labels: ✅ Approved

#240 Add 'update' subheadings for docker
  docs/install/docker.md
Labels: ✅ Approved

#242 Update Docs re Global Keyboard Shortcuts
  docs/getting-started/tipstricks.md
Labels: ✅ Approved

#243 Update Docs re delete Rules
  docs/budgeting/rules/index.md
Labels: ✅ Approved

#244 A tour of actual - small update
  docs/tour/index.md
Labels: ✅ Approved

#245 Describe how to access "Settings"
  docs/tour/settings.md
Labels: ✅ Approved

#228 Spellchecker CI
  .github/actions/spelling/README.md
  .github/actions/spelling/advice.md
  .github/actions/spelling/allow/contributers.txt
  .github/actions/spelling/allow/keywords.txt
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  .github/actions/spelling/line_forbidden.patterns
  .github/actions/spelling/patterns.txt
  .github/actions/spelling/reject.txt
  .github/workflows/spelling.yml
  blog/2023-01-12-release-23.1.12.md
  blog/2023-03-09-release-23.3.0.md
  blog/2023-03-13-release-23.3.2.md
  blog/2023-07-04-release-23.7.0.md
  docs-sidebar.js
  docs/api/reference.md
  docs/backup-restore/backup.md
  docs/backup-restore/restore.md
  docs/budgeting/credit-cards.md
  docs/budgeting/joint-accounts.md
  docs/budgeting/returns-and-reimbursements.md
  docs/contributing/index.md
  docs/contributing/project-details/architecture.md
  docs/contributing/windows.md
  docs/experimental/goal-templates.md
  docs/getting-started/manage-files.md
  docs/getting-started/tips-tricks.md
  docs/releases.md
  src/pages/index.js
  static/_redirects
Labels: 🔍 Ready for Review

#246 Filters - Example of Date Dropdown
  docs/reports-filters/filters.md
  static/img/filtering/Dates1@2x.png
  static/img/filtering/Dates2@2x.png
Labels: ✅ Approved

#247 Explanation of Filter Dropdowns
  docs/reports-filters/filters.md
Labels: ✅ Approved

#248 Fix markup of release note template for contributing docs
  docs/contributing/index.md
Labels: ✅ Approved

#249 Issue 236 - Settings page images missing highlighted callouts
  docs/tour/settings.md
  static/img/using-actual/settings-1.png
  static/img/using-actual/settings-2.png
  static/img/using-actual/settings-3.png
  static/img/using-actual/settings-advanced.png
  static/img/using-actual/settings-encryption.png
  static/img/using-actual/settings-export.png
  static/img/using-actual/settings-formatting.png
Labels: ✅ Approved

#241 Fix documentation for keeping negative balances in a category
  docs/budgeting/index.md
Labels: ✅ Approved

#252 Rewrite managing credit cards page
  docs-sidebar.js
  docs/budgeting/credit-cards.md
  docs/budgeting/credit-cards/carrying-debt.md
  docs/budgeting/credit-cards/index.md
Labels: 🔍 Ready for Review, ✅ Approved

#253 Goals: add blurb for previous flag, clean up confusing note
  docs/experimental/goal-templates.md
Labels: 🔍 Ready for Review
