Repository actualbudget/docs, pull requests merged in 2023-04, with the labels that each got.

#144 Update all Docker Hub references to new actualbudget organization
  docs/Installing/Docker.md
  docs/Installing/fly/Fly-image.md
Labels: ✅ Approved

#146 Add a page about configuring server debug logging
  docs/Installing/Configuration.md
  docs/Troubleshooting/Server.md
  sidebars.js
Labels: ✅ Approved

#142 Fly: add instruction for new upsell
  docs/Installing/fly/Fly-image.md
Labels: ✅ Approved

#145 Add doc to backup page about how to reduce backup size
  docs/Backup-Restore/Backups.md
Labels: ✅ Approved

#148 :bookmark: (23.4.0) release notes
  docs/Getting-Started/using-actual/index.md
  docs/Release-Notes.md
Labels: ✅ Approved

#150 :pencil: update release instructions
  docs/Developers/releasing.md
Labels: ✅ Approved

#153 :bookmark: (23.4.1) fix rule creation from transaction list
  README.md
  docs/Accounts/addaccount.md
  docs/Accounts/connecting-your-bank.md
  docs/Backup-Restore/Backups.md
  docs/Budgeting/returnsandreimbursements.md
  docs/Developers/Building-Windows.md
  docs/Release-Notes.md
Labels: ✅ Approved

#154 Add step to create a GitHub release when publishing a release
  docs/Developers/releasing.md
Labels: ✅ Approved

#155 fly launch cd clarification - resolves #140
  docs/Installing/fly/Fly-image.md
Labels: ✅ Approved

#151 Changed wording on 'by' matches section
  docs/Advanced/Experimental-Features/goal-templates.md
Labels: 🔍 Ready for Review

#158 Goals: Added 'schedule' keyword to syntax chart
  docs/Advanced/Experimental-Features/goal-templates.md
Labels: 🔍 Ready for Review

#159 :bookmark: (23.4.2) revert back to old autocomplete & keyboard shortcut fix
  docs/Release-Notes.md
Labels: ✅ Approved

#160 Fix table in goal template docs
  docs/Advanced/Experimental-Features/goal-templates.md
Labels: 🔍 Ready for Review, ✅ Approved

#147 Additions to keyboard shortcuts
  docs/Getting-Started/tipstricks.md
Labels: ✅ Approved

#165 View on Hover
  docs/Budgeting/categories.md
  static/img/categories/CategoryAddNote.png
  static/img/categories/CategoryEditNote.png
  static/img/categories/CategoryViewNoteHover.png
Labels: 🔍 Ready for Review, ✅ Approved

#164 Update addaccount.md
  docs/Accounts/addaccount.md
Labels: ✅ Approved

#152 Add percentage based targets to table
  docs/Advanced/Experimental-Features/goal-templates.md
Labels: ✅ Approved

#163 Demo Budget
  docs/Getting-Started/migration/actual-import.md
  docs/index.md
  sidebars.js
  static/test-budget.zip
Labels: 🔍 Ready for Review
