Repository actualbudget/docs, pull requests merged in 2023-01, with the labels that each got.

#79 Cleared Rules example
  docs/Budgeting/rules/rules-custom.md
  docs/Budgeting/rules/rules.md
  static/img/custom-rules-2.png
Labels: ✅ Approved

#77 Docker compose with nginx reverse proxy
  docs/Installing/DockerWithNginx.md
  sidebars.js
Labels: 🔍 Ready for Review

#36 Using Actual
  docs/Getting-Started/using-actual/accounts.md
  docs/Getting-Started/using-actual/budget.md
  docs/Getting-Started/using-actual/files.md
  docs/Getting-Started/using-actual/overview.md
  docs/Getting-Started/using-actual/schedules.md
  docs/Getting-Started/using-actual/settings.md
  docs/Getting-Started/using-actual/sidebar.md
  sidebars.js
  static/img/cleared-uncleared-expand.png
  static/img/using-actual/budget-account-register.png
  static/img/using-actual/budget-category-heading.png
  static/img/using-actual/budget-category.png
  static/img/using-actual/budget-list.png
  static/img/using-actual/budget-main.png
  static/img/using-actual/budget-month-overview.png
  static/img/using-actual/budget-month-selector.png
  static/img/using-actual/budget-months.png
  static/img/using-actual/budget-sidebar-accounts.png
  static/img/using-actual/budget-sidebar.png
  static/img/using-actual/budget-sync-status.png
  static/img/using-actual/budget.png
  static/img/using-actual/file-list.png
  static/img/using-actual/settings-1.png
  static/img/using-actual/settings-2.png
  static/img/using-actual/settings-3.png
Labels: documentation, waiting-review, 🔍 Ready for Review

#86 Add documentation for duplicating transactions, tweak bulk editing transactions page
  docs/Accounts/Transactions/bulk-editing-transactions.md
  static/img/duplicate-transactions.png
Labels: 🔍 Ready for Review

#87 update discord links
  docs/Budgeting/rules/rules-custom.md
  docs/Installing/fly/Fly-image.md
  docs/Installing/fly/Fly.io.md
Labels: ✅ Approved
