Repository actualbudget/docs, pull requests merged in 2024-11, with the labels that each got.

#481 🔖 (24.11.0)
  .github/actions/spelling/expect.txt
  blog/2024-11-03-release-24.11.0.md
  blog/authors.yml
  docs/releases.md
  static/img/authors/jfdoming.jpeg
Labels: :white_check_mark: Approved

#478 incorrect box specified from the photo
  docs/tour/accounts.md
Labels: :white_check_mark: Approved

#484 [WIP] Fix date on latest release post
  blog/2024-11-03-release-24.11.0.md
Labels: :construction: WIP

#482 docs: Explain running balance is shown only with descending date
  docs/getting-started/tips-tricks.md
Labels: :mag: Ready for review

#488 [WIP] docs: fix typo
  docs/getting-started/starting-fresh.md
Labels: :construction: WIP

#492 Update local.md
  docs/install/local.md
Labels: :white_check_mark: Approved

#494 [WIP] Update/docs
  docs/getting-started/starting-fresh.md
  static/img/tips-tricks/months-selector.png
Labels: :construction: WIP

#499 [WIP] Update index.md
  docs/tour/index.md
Labels: :construction: WIP

#500 Update budget.md
  docs/tour/budget.md
Labels: :mag: Ready for review

#502 Update accounts.md
  docs/tour/accounts.md
Labels: :mag: Ready for review

#503 Update reports.md
  docs/tour/reports.md
Labels: :mag: Ready for review

#501 Update accounts.md
  docs/tour/accounts.md
Labels: :mag: Ready for review

#507 Update schedules.md
  docs/tour/schedules.md
Labels: :white_check_mark: Approved

#508 Update envelope-budgeting.md
  docs/getting-started/envelope-budgeting.md
Labels: :white_check_mark: Approved

#509 Update roadmap-for-new-users.md
  docs/getting-started/roadmap-for-new-users.md
Labels: :white_check_mark: Approved

#510 Update payees.md
  docs/tour/payees.md
Labels: :white_check_mark: Approved

#513 [WIP] Update index.md
  docs/config/index.md
Labels: :construction: WIP

#512 Update fly.md
  docs/install/fly.md
Labels: :white_check_mark: Approved

#511 Update pikapods.md
  docs/install/pikapods.md
Labels: :white_check_mark: Approved

#519 Update index.md
  docs/budgeting/index.md
Labels: :white_check_mark: Approved

#518 Update index.md
  docs/budgeting/index.md
Labels: :mag: Ready for review

#517 Update starting-fresh.md
  docs/getting-started/starting-fresh.md
Labels: :mag: Ready for review

#516 Update nynab.md
  docs/migration/nynab.md
Labels: :white_check_mark: Approved

#520 Small fix to wording in Pikapods page
  docs/install/pikapods.md
Labels: :white_check_mark: Approved

#514 Update https.md
  docs/config/https.md
Labels: :white_check_mark: Approved

#522 whitespace fixes
  blog/2023-12-15-automate.md
  blog/2024-03-25-automate-twist.md
  blog/2024-07-01-ynab_v_actual.md
  docs/accounts/index.md
  docs/accounts/reconciliation.md
  docs/advanced/bank-sync.md
  docs/advanced/bank-sync/gocardless.md
  docs/advanced/bank-sync/simplefin.md
  docs/advanced/http-header-auth.md
  docs/budgeting/categories.md
  docs/budgeting/credit-cards/carrying-debt.md
  docs/budgeting/credit-cards/index.md
  docs/budgeting/index.md
  docs/budgeting/rules/custom.md
  docs/community-repos.md
  docs/config/https.md
  docs/config/index.md
  docs/contributing/project-details/architecture.md
  docs/contributing/project-details/electron.md
  docs/contributing/project-details/migrations.md
  docs/contributing/writing-docs.md
  docs/experimental/goal-templates.md
  docs/experimental/monthly-cleanup.md
  docs/experimental/tracking-budget.md
  docs/getting-started/envelope-budgeting.md
  docs/getting-started/roadmap-for-new-users.md
  docs/getting-started/starting-fresh.md
  docs/getting-started/sync.md
  docs/getting-started/tips-tricks.md
  docs/index.md
  docs/install/index.md
  docs/install/local.md
  docs/install/pikapods.md
  docs/migration/nynab.md
  docs/reports/custom-reports.md
  docs/schedules.md
  docs/tour/accounts.md
  docs/tour/budget.md
  docs/tour/payees.md
  docs/tour/reports.md
  docs/transactions/transfers.md
  docs/troubleshooting/reset_password.md
  docs/vision.md
Labels: :white_check_mark: Approved

#521 fix some spelling issues, standardis(z)e to US English
  .github/actions/spelling/expect.txt
  README.md
  blog/2023-01-12-release-23.1.12.md
  blog/2023-09-02-release-23.9.0.md
  blog/2023-10-03-release-23.10.0.md
  blog/2023-12-03-release-23.12.0.md
  blog/2024-03-03-release-24.3.0.md
  blog/2024-04-01-release-24.4.0.md
  blog/2024-06-03-release-24.6.0.md
  blog/2024-07-02-release-24.7.0.md
  blog/2024-09-03-release-24.9.0.md
  docs/accounts/reconciliation.md
  docs/advanced/restart.md
  docs/advanced/scripts/modify-transfers.md
  docs/api/index.md
  docs/api/reference.md
  docs/backup-restore/restore.md
  docs/community-repos.md
  docs/config/index.md
  docs/contributing/index.md
  docs/contributing/project-details/database.md
  docs/contributing/project-details/electron.md
  docs/contributing/project-details/index.md
  docs/contributing/project-details/migrations.md
  docs/contributing/releasing.md
  docs/contributing/writing-docs.md
  docs/experimental/goal-templates.md
  docs/getting-started/starting-fresh.md
  docs/install/fly.md
  docs/install/index.md
  docs/install/pikapods.md
  docs/migration/index.md
  docs/migration/nynab.md
  docs/releases.md
  docs/reports/custom-reports.md
  docs/tour/accounts.md
  docs/transactions/bulk-editing.md
  docs/transactions/filters.md
  docs/troubleshooting/reset_password.md
  src/pages/download.md
Labels: :mag: Ready for review
