Repository actualbudget/docs, pull requests merged in 2024-09, with the labels that each got.

#444 :bookmark: (24.9.0)
  .github/actions/spelling/allow/keywords.txt
  blog/2024-09-03-release-24.9.0.md
  docs/releases.md
Labels: :white_check_mark: Approved

#448 [WIP] Spelling of "Synology"
  docs/getting-started/roadmap-for-new-users.md
Labels: :construction: WIP

#446 Added info on how Pikapods updates
  docs/install/pikapods.md
Labels: :white_check_mark: Approved

#443 Remove compose down from update instructions
  docs/install/docker.md
Labels: :mag: Ready for review

#398 basics of text style guide for consistent tone when writing.
  .github/actions/spelling/allow/keywords.txt
  .gitignore
  README.md
  docs-sidebar.js
  docs/contributing/writing-docs.md
  static/img/repo/annotation-boxes-over-arrows.png
  static/img/repo/annotation-colour-boxes.png
  static/img/repo/annotation-colours.png
  static/img/repo/annotation-free-hand.png
  static/img/repo/annotation-highlights-are-bad.png
  static/img/repo/annotation-highlights-ligth-theme.png
  static/img/repo/annotation-steps.png
  static/img/repo/highlighting.png
Labels: :white_check_mark: Approved

#405 Add web app install docs
  docs/install/index.md
Labels: :mag: Ready for review

#388 [WIP] Updated the local installation file
  docs/install/local.md
Labels: :construction: WIP

#450 Update notes on self signed certificates for desktop app
  .github/actions/spelling/allow/keywords.txt
  docs/config/https.md
Labels: :white_check_mark: Approved

#442 Joint account streategy changes
  .gitignore
  docs/budgeting/joint-accounts.md
Labels: :white_check_mark: Approved

#429 Reorganising the menu items
  .gitignore
  docs-sidebar.js
  docs/getting-started/starting-fresh.md
  docs/reports-filters/index.md
  docs/reports/custom-reports.md
  docs/reports/index.md
  docs/schedules.md
  docs/tour/accounts.md
  docs/tour/reports.md
  docs/tour/schedules.md
  docs/transactions/filters.md
Labels: :mag: Ready for review

#451 Added Link to UnRAID SSL setup in /docs/install/index.md
  docs/install/index.md
Labels: :white_check_mark: Approved

#455 [WIP] docs: fix typos
  docs/advanced/bank-sync.md
  docs/advanced/scripts/modify-transfers.md
  docs/budgeting/joint-accounts.md
  docs/budgeting/rules/index.md
  docs/contributing/windows.md
  docs/getting-started/starting-fresh.md
  docs/releases.md
  docs/tour/user-interface.md
Labels: :construction: WIP

#457 Update community-repos.md to remove simplefin community in favor of official simplefin integration
  docs/community-repos.md
Labels: :white_check_mark: Approved

#456 docs: fix more typos
  docs/tour/accounts.md
  docs/tour/budget.md
Labels: :white_check_mark: Approved
