Repository actualbudget/docs, pull requests merged in 2024-08, with the labels that each got.

#421 :bookmark: (24.8.0)
  .github/actions/spelling/allow/keywords.txt
  blog/2024-08-02-release-24.8.0.md
  docs/releases.md
Labels: :white_check_mark: Approved

#418 Added Cost Optimization Section for Fly Install Instructions
  docs/install/fly.md
Labels: :white_check_mark: Approved

#424 Update fly.io pricing information
  docs/install/index.md
Labels: :white_check_mark: Approved

#420 Add documentation for holdBudgetForNextMonth and resetBudgetHold
  docs/api/reference.md
Labels: :white_check_mark: Approved

#423 Converts Norwegian Trumf Visa PDF invoice to an AB friendly CSV file
  .github/actions/spelling/allow/keywords.txt
  docs/community-repos.md
Labels: :white_check_mark: Approved

#425 Update report budget docs
  docs-sidebar.js
  docs/experimental/tracking-budget.md
  static/img/report-budget-7.png
  static/img/tracking-budget-1.png
  static/img/tracking-budget-2.png
  static/img/tracking-budget-3.png
  static/img/tracking-budget-4.png
  static/img/tracking-budget-5.png
  static/img/tracking-budget-6.png
  static/img/tracking-budget-7.png
Labels: :white_check_mark: Approved

#426 [WIP] GoCardless clarification on number of requests on the free tier + alt-text of images + fix a step number
  docs/advanced/bank-sync.md
Labels: :construction: WIP

#427 [WIP] Fix typo in the budget.md
  docs/tour/budget.md
Labels: :construction: WIP

#428 :pencil: highlight that Actual does not have a HTTP API
  docs/api/index.md
  docs/faq.md
Labels: :white_check_mark: Approved

#430 Update Mac links on Downloads page
  src/pages/download.md
Labels: :mag: Ready for review

#432 Make note/link about SimpleFIN in the bank docs page.
  docs/advanced/bank-sync.md
Labels: :mag: Ready for review

#422 update rules page w/ link to regex tutorial
  docs/budgeting/rules/index.md
Labels: :white_check_mark: Approved

#431 Add i18n documentation
  README.md
  docs-sidebar.js
  docs/contributing/i18n.md
Labels: :white_check_mark: Approved

#434 Remove namespace from i18n example
  docs/contributing/i18n.md
Labels: :white_check_mark: Approved

#436 Adding instructions for the windows store release
  docs/contributing/releasing.md
Labels: :white_check_mark: Approved

#438 [WIP] Clarify post-processing in `add/importTransactions`
  docs/api/reference.md
Labels: :construction: WIP

#435 Add FAQ entry on how to add GoCardless bank to limited history list.
  docs/advanced/bank-sync.md
Labels: :white_check_mark: Approved

#439 Add actualbudget home assistant integration link
  docs/community-repos.md
Labels: :white_check_mark: Approved

#441 Add note about new #community-projects Discord channel.
  docs/community-repos.md
Labels: :white_check_mark: Approved

#396 Update docs to be time-neutral by removing outdated references, update related screenshots to where these issues occured
  docs/budgeting/categories.md
  docs/reports-filters/filters.md
  static/img/categories/CategoriesHidden.png
  static/img/categories/CategoryGroupAddCategory.png
  static/img/categories/CategoryToggleHidden.png
  static/img/categories/RenameCategoryOptions.png
Labels: :white_check_mark: Approved
