Repository actualbudget/docs, pull requests merged in 2024-12, with the labels that each got.

#532 Update transfers.md
  docs/transactions/transfers.md
Labels: :white_check_mark: Approved

#531 Update filters.md
  docs/transactions/filters.md
Labels: :white_check_mark: Approved

#529 Update schedules.md
  docs/schedules.md
Labels: :white_check_mark: Approved

#530 Update index.md
  docs/accounts/index.md
Labels: :white_check_mark: Approved

#528 Update restart.md
  docs/advanced/restart.md
Labels: :white_check_mark: Approved

#527 Update joint-accounts.md
  docs/budgeting/joint-accounts.md
Labels: :white_check_mark: Approved

#526 Update carrying-debt.md
  docs/budgeting/credit-cards/carrying-debt.md
Labels: :white_check_mark: Approved

#525 Update returns-and-reimbursements.md
  docs/budgeting/returns-and-reimbursements.md
Labels: :white_check_mark: Approved

#543 Update restore.md
  docs/backup-restore/restore.md
Labels: :white_check_mark: Approved

#542 Update backup.md
  docs/backup-restore/backup.md
Labels: :white_check_mark: Approved

#540 Update index.md
  docs/reports/index.md
Labels: :white_check_mark: Approved

#539 Update modify-transfers.md
  docs/advanced/scripts/modify-transfers.md
Labels: :white_check_mark: Approved

#538 Update simplefin.md
  docs/advanced/bank-sync/simplefin.md
Labels: :white_check_mark: Approved

#537 Update bulk-editing.md
  docs/transactions/bulk-editing.md
Labels: :white_check_mark: Approved

#536 Update payees.md
  docs/transactions/payees.md
Labels: :white_check_mark: Approved

#535 Update reconciliation.md
  docs/accounts/reconciliation.md
Labels: :white_check_mark: Approved

#524 Update categories.md
  docs/budgeting/categories.md
Labels: :white_check_mark: Approved

#523 Update reverse-proxies.md
  docs/config/reverse-proxies.md
Labels: :white_check_mark: Approved

#497 adds hint for missing date formats
  docs/transactions/importing.md
Labels: :white_check_mark: Approved

#534 Update importing.md
  docs/transactions/importing.md
Labels: :white_check_mark: Approved

#541 Update custom-reports.md
  docs/reports/custom-reports.md
Labels: :white_check_mark: Approved

#546 Update sync.md
  docs/getting-started/sync.md
Labels: :white_check_mark: Approved

#533 Update index.md
  docs/budgeting/rules/index.md
Labels: :white_check_mark: Approved

#545 🔖 (24.12.0)
  .github/actions/spelling/allow/contributers.txt
  .github/actions/spelling/expect.txt
  blog/2024-12-05-release-24-12-0.md
  blog/authors.yml
  docs/releases.md
  static/img/authors/matt-fidd.jpeg
Labels: :white_check_mark: Approved

#552 fix version number for v24.12.0
  docs/releases.md
Labels: :mag: Ready for review

#551 Update goal-templates.md
  docs/experimental/goal-templates.md
Labels: :white_check_mark: Approved

#550 Update tracking-budget.md
  docs/experimental/tracking-budget.md
Labels: :white_check_mark: Approved

#549 Update monthly-cleanup.md
  docs/experimental/monthly-cleanup.md
Labels: :white_check_mark: Approved

#548 Update manage-files.md
  docs/getting-started/manage-files.md
Labels: :white_check_mark: Approved

#553 [WIP] fix titles in release notes
  docs/releases.md
Labels: :construction: WIP

#483 Update the tracking budget page so the feature can be released.
  docs-sidebar.js
  docs/getting-started/tracking-budget.md
  docs/settings/index.md
Labels: :mag: Ready for review, Merge at Release

#558 fix merge bug
  docs/getting-started/tracking-budget.md
Labels: :mag: Ready for review

#562 Update index.md
  docs/api/actual-ql/index.md
Labels: :white_check_mark: Approved

#577 Update windows.md
  docs/contributing/windows.md
Labels: :white_check_mark: Approved

#563 Update functions.md
  docs/api/actual-ql/functions.md
Labels: :white_check_mark: Approved

#564 Update examples.md
  docs/api/actual-ql/examples.md
Labels: :white_check_mark: Approved

#565 Update server.md
  docs/troubleshooting/server.md
Labels: :white_check_mark: Approved

#567 Update reset_password.md
  docs/troubleshooting/reset_password.md
Labels: :white_check_mark: Approved

#568 Update edge-browser.md
  docs/troubleshooting/edge-browser.md
Labels: :white_check_mark: Approved

#571 Update database.md
  docs/contributing/project-details/database.md
Labels: :white_check_mark: Approved

#572 Update feature-flags.md
  docs/contributing/project-details/feature-flags.md
Labels: :white_check_mark: Approved

#574 Update i18n.md
  docs/contributing/i18n.md
Labels: :white_check_mark: Approved

#575 Update preview-builds.md
  docs/contributing/preview-builds.md
Labels: :white_check_mark: Approved

#576 Update releasing.md
  docs/contributing/releasing.md
Labels: :white_check_mark: Approved

#578 Update writing-docs.md
  docs/contributing/writing-docs.md
Labels: :white_check_mark: Approved

#579 Update new-core-contributors-guide.md
  docs/contributing/leadership/new-core-contributors-guide.md
Labels: :white_check_mark: Approved

#573 Update migrations.md
  docs/contributing/project-details/migrations.md
Labels: :white_check_mark: Approved

#570 Update index.md
  docs/contributing/project-details/index.md
Labels: :white_check_mark: Approved

#569 Update index.md
  docs/contributing/index.md
Labels: :white_check_mark: Approved

#560 Update reconciliation instructions and images to reflect current UI
  docs/accounts/reconciliation.md
  static/img/reconcile/reconcile-11.png
  static/img/reconcile/reconcile-3.png
Labels: :white_check_mark: Approved

#554 Update types.js
  docs/api/types.js
Labels: :white_check_mark: Approved

#555 Update tips-tricks.md
  docs/getting-started/tips-tricks.md
Labels: :white_check_mark: Approved

#556 Update index.md
  docs/api/index.md
Labels: :white_check_mark: Approved

#557 Update reference.md
  docs/api/reference.md
Labels: :white_check_mark: Approved

#583 Add example of orderBy with a descending order
  docs/api/actual-ql/functions.md
Labels: :white_check_mark: Approved

#584 [WIP] fix envelope budgeting numbering typo
  docs/getting-started/envelope-budgeting.md
Labels: :construction: WIP

#559 Add dashboard and tracking budget links to latest release notes
  blog/2024-12-05-release-24-12-0.md
  docs/releases.md
Labels: :white_check_mark: Approved

#587 [WIP] Closes #585
  docs-sidebar.js
Labels: :construction: WIP
