Repository actualbudget/docs, pull requests merged in 2024-07, with the labels that each got.

#390 Explain condition types on Rules and Filtering pages
  docs/budgeting/rules/index.md
  docs/reports-filters/filters.md
  static/img/filtering/conditions-1.png
  static/img/filtering/conditions-2.png
  static/img/filtering/conditions-3.png
Labels: :white_check_mark: Approved

#397 Readme cleanup, update to release notes, ʻlight modeʻ screenshots
  README.md
Labels: :white_check_mark: Approved

#393 Extended the PikaPods documentation for non-technical users
  docs/install/pikapods.md
  static/img/a-tour-of-actual/server-connecting-first-time.png
  static/img/pikapods-setup/pikapods-1-register-login.png
  static/img/pikapods-setup/pikapods-2-register-name.png
  static/img/pikapods-setup/pikapods-3-register-thanks-for-signup.png
  static/img/pikapods-setup/pikapods-4-email-activation.png
  static/img/pikapods-setup/pikapods-4b-email-welcome.png
  static/img/pikapods-setup/pikapods-5-login-screen.png
  static/img/pikapods-setup/pikapods-6-add-pod-basics.png
  static/img/pikapods-setup/pikapods-7-add-pod-resoruces.png
  static/img/pikapods-setup/pikapods-8-running-pod.png
Labels: :white_check_mark: Approved

#395 Roadmaps for new users
  .github/actions/spelling/allow/keywords.txt
  docs-sidebar.js
  docs/getting-started/roadmap-for-new-users.md
  docs/index.md
Labels: :white_check_mark: Approved

#400 Activating HTTPs - header levels was wrong - no content has been changed.
  docs/config/https.md
Labels: :mag: Ready for review

#359 Add a download page to the website
  .github/actions/spelling/allow/keywords.txt
  docusaurus.config.js
  src/pages/download.md
  static/img/apple.svg
  static/img/linux.svg
  static/img/win.svg
Labels: 🔍 Ready for Review, :white_check_mark: Approved

#406 Added various links to the Community Projects page
  .github/actions/spelling/allow/keywords.txt
  docs/community-repos.md
Labels: :white_check_mark: Approved

#377 Add API docs for getLocalbudgets() and getRemoteBudgets().
  docs/api/reference.md
  docs/api/types.js
Labels: :white_check_mark: Approved

#404 Add `mergePayees` to the API reference
  docs/api/reference.md
Labels: :white_check_mark: Approved

#403 Add getAccountBalance() API documentation
  docs/api/reference.md
Labels: :white_check_mark: Approved

#407 [WIP] Add actual budget backup to community projects
  docs/community-repos.md
Labels: :construction: WIP

#402 Revamp of A tour of actual
  docs-sidebar.js
  docs/settings/index.md
  docs/tour/accounts.md
  docs/tour/budget.md
  docs/tour/files.md
  docs/tour/index.md
  docs/tour/overview.md
  docs/tour/payees.md
  docs/tour/reports.md
  docs/tour/rules.md
  docs/tour/schedules.md
  docs/tour/user-interface.md
  static/img/a-tour-of-actual/tour-account-register-adding-transaction.png
  static/img/a-tour-of-actual/tour-account-register-filter.png
  static/img/a-tour-of-actual/tour-account-register-header.png
  static/img/a-tour-of-actual/tour-account-register-overview.png
  static/img/a-tour-of-actual/tour-account-register-selected-transactions.png
  static/img/a-tour-of-actual/tour-budget-calendar-choose.png
  static/img/a-tour-of-actual/tour-budget-calendar.png
  static/img/a-tour-of-actual/tour-budget-details.png
  static/img/a-tour-of-actual/tour-budget-overview.png
  static/img/a-tour-of-actual/tour-budget-top-expanded.png
  static/img/a-tour-of-actual/tour-budget-top-minimized.png
  static/img/a-tour-of-actual/tour-overview-of-user-interface.png
  static/img/a-tour-of-actual/tour-overview-sidebar.png
  static/img/a-tour-of-actual/tour-overview-top-right.png
  static/img/a-tour-of-actual/tour-payees-delete-merge.png
  static/img/a-tour-of-actual/tour-payees-overview.png
  static/img/a-tour-of-actual/tour-reports-cashflow.png
  static/img/a-tour-of-actual/tour-reports-daily-expenses-graph.png
  static/img/a-tour-of-actual/tour-reports-daily-expenses-table.png
  static/img/a-tour-of-actual/tour-reports-net-worth.png
  static/img/a-tour-of-actual/tour-reports-overview.png
  static/img/a-tour-of-actual/tour-rules-overview.png
  static/img/a-tour-of-actual/tour-schedules-overview.png
Labels: :white_check_mark: Approved

#410 :pencil: update core contributor list
  docs/contributing/index.md
Labels: :white_check_mark: Approved

#401 add section for goal template directive
  docs/experimental/goal-templates.md
Labels: :white_check_mark: Approved

#414 📝 update the API docs information
  docs/api/reference.md
  docs/contributing/index.md
Labels: :white_check_mark: Approved

#412 Update custom-reports.md for typo
  docs/reports-filters/custom-reports.md
Labels: :white_check_mark: Approved

#411 Update reports.md to fix typo
  docs/tour/reports.md
Labels: :white_check_mark: Approved

#413 Move ActualTap to ActualTap-py
  docs/community-repos.md
Labels: :white_check_mark: Approved
