Repository actualbudget/docs, pull requests merged in 2024-03, with the labels that each got.

#325 Update goal-templates.md
  docs/experimental/goal-templates.md
Labels: ✅ Approved

#327 :bookmark: (24.3.0)
  .github/actions/spelling/allow/keywords.txt
  blog/2024-02-06-release-24.3.0.md
  docs/releases.md
Labels: ✅ Approved

#326 Rollover notes: Update for PR 2409
  docs/experimental/monthly-cleanup.md
Labels: ✅ Approved

#330 Capitalize "actual" on line 7
  docs/contributing/project-details/database.md
Labels: ✅ Approved

#331 Update index.md - "Using the API"
  docs/api/index.md
Labels: ✅ Approved

#329 Update categories.md
  docs/budgeting/categories.md
Labels: ✅ Approved

#328 add financier migration repo
  docs/community-repos.md
Labels: ✅ Approved

#332 Update reverse-proxies.md
  docs/config/reverse-proxies.md
Labels: 🔍 Ready for Review

#335 Update https.md
  docs/config/https.md
Labels: ✅ Approved

#333 Clarify that goal schedule template should not include braces
  docs/experimental/goal-templates.md
Labels: 🔍 Ready for Review

#336 Update local.md
  docs/install/local.md
Labels: ✅ Approved

#321 Add docs on ability to create transfer from two existing transactions
  docs/transactions/transfers.md
  static/img/transfers/make-transfer-tooltip.png
  static/img/transfers/payees-dropdown.png
  static/img/transfers/transfer-complete.png
Labels: ✅ Approved

#338 Blog Post: Templates with a twist for weekly targets
  blog/2024-03-25-automate-twist.md
  static/img/blog/twist-1.png
  static/img/blog/twist-2.png
  static/img/blog/twist-3.png
  static/img/blog/twist-4.png
  static/img/blog/twist-5.png
  yarn.lock
Labels: 🔍 Ready for Review

#339 Update the FAQ to reflect the new mobile layout feature
  docs/faq.md
Labels: 🔍 Ready for Review, ✅ Approved

#340 :fire: remove non-existing api methods from api docs
  docs/api/reference.md
Labels: ✅ Approved
