Repository actualbudget/docs, pull requests merged in 2025-01, with the labels that each got.

#504 Use consistent terms regarding on-budget and off-budget accounts
  docs/accounts/index.md
  docs/accounts/reconciliation.md
  docs/api/reference.md
  docs/budgeting/joint-accounts.md
  docs/budgeting/returns-and-reimbursements.md
  docs/getting-started/starting-fresh.md
  docs/reports/custom-reports.md
  docs/tour/reports.md
  docs/tour/sidebar.md
  docs/tour/user-interface.md
  static/img/add-account/AccountNameEdit.png
  static/img/add-account/AddAccount.png
  static/img/add-account/CreateAccount1.png
  static/img/add-account/CreateAccount@2x.png
  static/img/add-account/SidebarAccountList@2x.png
Labels: :white_check_mark: Approved

#591 [WIP] Fixing spellbot errors to prevent #561 to go stale
  .github/actions/spelling/allow/keywords.txt
Labels: :construction: WIP

#489 Update local.md - Adding Linux systemd unit file instructions
  .github/actions/spelling/expect.txt
  docs/install/local.md
Labels: :white_check_mark: Approved

#592 [WIP] Fixing spellbot errors to prevent #561 to go stale
  .github/actions/spelling/allow/keywords.txt
Labels: :construction: WIP

#561 Update index.md
  docs/api/actual-ql/index.md
Labels: :white_check_mark: Approved

#595 :pencil: add UnderKoen and RubenOlsen to maintainer list
  docs/contributing/index.md
Labels: :white_check_mark: Approved

#600 Fixing #582 Migration Link Broken by clarifying the content.
  docs/faq.md
  docs/install/index.md
  docs/migration/index.md
Labels: :white_check_mark: Approved

#598 Adding Portuguese prepaid meal card tracking from @rodriguestiago0.
  .github/actions/spelling/allow/keywords.txt
  docs/community-repos.md
Labels: :white_check_mark: Approved

#601 🔖 (25.1.0)
  .github/actions/spelling/expect.txt
  blog/2025-01-05-release-25-1-0.md
  docs/releases.md
Labels: :white_check_mark: Approved, Merge at Software Release

#605 Update releasing.md for release notes
  docs/contributing/releasing.md
Labels: :mag: Ready for review

#473 #470 - added section on Pay Yourself First strategy
  docs/accounts/reconciliation.md
  docs/budgeting/credit-cards/carrying-debt.md
  docs/budgeting/joint-accounts.md
  docs/contributing/writing-docs.md
  docs/getting-started/envelope-budgeting.md
Labels: :white_check_mark: Approved

#607 Update instructions for enabling Tracking Budget
  docs/getting-started/tracking-budget.md
Labels: :white_check_mark: Approved

#496 document multi-user usage of same budget file
  docs/budgeting/joint-accounts.md
  docs/getting-started/sync.md
Labels: :white_check_mark: Approved

#599 Export from commercial Actual Budget app-page and associated image is no longer relevant for the documentation.
  docs-sidebar.js
  docs/migration/actual-import.md
  static/img/migrating/actual-export@2x.png
Labels: :white_check_mark: Approved

#602 Community repos ICS Cards and Amazon Order CVS file generators.
  docs/community-repos.md
Labels: :white_check_mark: Approved

#589 Fixing #566 - documenting ACTUAL_DATA_DIR environment variable.
  docs/config/index.md
Labels: :white_check_mark: Approved

#609 [WIP] docs: changed effect (noun) to affect (verb)
  docs/accounts/index.md
Labels: :construction: WIP

#610 Update translation docs
  .github/actions/spelling/expect.txt
  docs/contributing/i18n.md
Labels: :white_check_mark: Approved

#606 reworking template docs
  docs/experimental/goal-templates.md
  static/img/goal-template/apply-template-category.png
  static/img/goal-template/apply-template-group.png
  static/img/goal-template/goal-indicator.png
Labels: :white_check_mark: Approved

#581 Add auth proxies config to the docs
  docs/advanced/http-header-auth.md
  docs/config/index.md
Labels: :white_check_mark: Approved, Merge at Software Release

#594 Add Page for Multi-Currency Support
  .github/actions/spelling/allow/keywords.txt
  docs-sidebar.js
  docs/budgeting/multi-currency.md
  static/img/multi-currency/account-name-and-note.png
  static/img/multi-currency/rule-1.png
  static/img/multi-currency/rule-2.png
  static/img/multi-currency/rule-action-normal-instructions.png
  static/img/multi-currency/rule-action-normal.png
  static/img/multi-currency/rule-action-template.png
  static/img/multi-currency/rule-action.png
  static/img/multi-currency/usage-convert.png
  static/img/multi-currency/usage-postconvert.png
  static/img/multi-currency/usage-preconvert.png
Labels: :white_check_mark: Approved

#611 [Goals]: tweaks for clarity and note on lines
  docs/experimental/goal-templates.md
Labels: :white_check_mark: Approved

#616 [WIP] Update envelope-budgeting.md
  docs/getting-started/envelope-budgeting.md
Labels: :construction: WIP

#614 [WIP] Update faq.md
  docs/faq.md
Labels: :construction: WIP

#622 Update reconciliation.md
  docs/accounts/reconciliation.md
Labels: :mag: Ready for review

#621 Fix link to main.ts in API docs.
  docs/api/index.md
Labels: :white_check_mark: Approved

#619 Update https.md
  docs/config/https.md
Labels: :white_check_mark: Approved

#615 Update envelope-budgeting.md
  docs/getting-started/envelope-budgeting.md
Labels: :white_check_mark: Approved

#617 Update 2024-07-01-ynab_v_actual.md
  blog/2024-07-01-ynab_v_actual.md
Labels: :white_check_mark: Approved
