Repository actualbudget/docs, pull requests merged in 2025-05, with the labels that each got.

#680 Docs for new sync-server npm package
  docs-sidebar.js
  docs/config/index.md
  docs/contributing/releasing.md
  docs/install/cli-tool.md
  docs/install/index.md
Labels: :white_check_mark: Approved

#687 🔖 (25.5.0)
  .github/actions/spelling/expect.txt
  blog/2025-05-03-release-25-5-0.md
  docs/releases.md
Labels: :mag: Ready for review

#689 [WIP] Minor tweaks to the Caddy compose file
  docs/config/reverse-proxies.md
Labels: :construction: WIP

#688 Ngrok reverse proxy docs
  docs/config/reverse-proxies.md
  docs/install/build-from-source.md
Labels: :mag: Ready for review, :white_check_mark: Approved, :warning: Changes requested

#691 Add link til Arch Linux User Repository (AUR) package
  docs/install/index.md
Labels: :mag: Ready for review, :white_check_mark: Approved

#692 change minimum version of Node.js to version 20
  docs/contributing/windows.md
  docs/install/build-from-source.md
Labels: :mag: Ready for review, :white_check_mark: Approved

#693 Fixing #663 Privacy Filter / Scramble and Hide data documenation
  docs/getting-started/tips-tricks.md
  static/img/tips-tricks/scrambled-clear-view.png
  static/img/tips-tricks/scrambled-scrambled-view.png
Labels: :mag: Ready for review, :white_check_mark: Approved

#694 Adding some fancy reporting dashboards to the front page
  docs/reports/custom-reports.md
  src/pages/index.js
  static/img/homepage/actual-report-dashboard-dark.png
  static/img/homepage/actual-report-dashboard-light.png
  static/img/reports/cr-fancy-example.png
Labels: :mag: Ready for review, :white_check_mark: Approved

#698 Fixing #608 by documenting the actual process.
  docs/backup-restore/restore.md
  static/img/backup-restore/restore-close-budget.png
  static/img/backup-restore/restore-import-file-choose-file.png
  static/img/backup-restore/restore-import-file-dialog.png
  static/img/backup-restore/restore-import-file-select-file.png
  static/img/backup-restore/restore-import-file.png
  static/img/backup-restore/restore-import-imported-budget.png
  static/img/restore/actual-config-10.png
  static/img/restore/actual-config-11.png
  static/img/restore/actual-config-7.png
  static/img/restore/actual-config-8.png
  static/img/restore/actual-config-9.png
Labels: :white_check_mark: approved

#697 Pocket ID tested with OAuth
  docs/experimental/oauth-auth.md
Labels: :white_check_mark: approved

#701 Update community-repos.md to add actual-userscripts
  .github/actions/spelling/expect.txt
  docs/community-repos.md
Labels: :mag: ready for review

#703 Fixing miscalculation
  docs/getting-started/envelope-budgeting.md
Labels: :white_check_mark: approved

#704 Fixed Typo on apache reverse proxy page
  docs/config/reverse-proxies.md
Labels: :white_check_mark: approved

#706 List Arch AUR packages
  .github/actions/spelling/expect.txt
  docs/install/index.md
Labels: :mag: ready for review

#707 Fix ambiguous examples in goal-templates page
  docs/experimental/goal-templates.md
Labels: :white_check_mark: approved
