Repository actualbudget/docs, pull requests merged in 2025-02, with the labels that each got.

#623 Add actual-budget-prometheus-exporter
  .github/actions/spelling/expect.txt
  docs/community-repos.md
Labels: :white_check_mark: Approved

#627 Add docs about releasing translations
  docs/contributing/releasing.md
Labels: :white_check_mark: Approved

#626 🔖 (25.2.0)
  .github/actions/spelling/expect.txt
  blog/2025-02-05-release-25-2-0.md
  docs/releases.md
Labels: :white_check_mark: Approved

#628 🔖 (25.2.1) fix desktop apps and reports page
  blog/2025-02-06-release-25-2-1.md
  docs/releases.md
Labels: :white_check_mark: Approved

#629 Documenting the repo move
  docs-sidebar.js
  docs/actual-server-repo-move.md
Labels: :mag: Ready for review, Merge at Software Release

#620 Updating references to Actual-Server to point to Actual repository
  docs/advanced/bank-sync/gocardless.md
  docs/contributing/project-details/index.md
  docs/contributing/releasing.md
  docs/install/docker.md
  docs/install/local.md
Labels: :white_check_mark: Approved

#630 Add docs for i18n on local install
  docs/install/local.md
Labels: :white_check_mark: Approved

#633 update reconciliation page
  docs/accounts/reconciliation.md
  static/img/reconcile/reconcile-1.png
  static/img/reconcile/reconcile-10.png
  static/img/reconcile/reconcile-11.png
  static/img/reconcile/reconcile-2.png
  static/img/reconcile/reconcile-3.png
  static/img/reconcile/reconcile-4.png
  static/img/reconcile/reconcile-5.png
  static/img/reconcile/reconcile-6.png
  static/img/reconcile/reconcile-7.png
  static/img/reconcile/reconcile-8.png
  static/img/reconcile/reconcile-9.png
Labels: :white_check_mark: Approved

#632 add docs for rule action templating experimental feature
  docs-sidebar.js
  docs/experimental/rule-templating.md
  static/img/experimental/rule-templating/enable-rule-templating-2.png
  static/img/experimental/rule-templating/enable-rule-templating.png
Labels: :white_check_mark: Approved

#636 add release dates to releases page
  docs/releases.md
Labels: :white_check_mark: Approved

#635 update filtering page
  docs/transactions/filters.md
  static/img/filtering/Dates1@2x.png
  static/img/filtering/Dates2@2x.png
  static/img/filtering/accounts.png
  static/img/filtering/accounts@2x.png
  static/img/filtering/conditions-1.png
  static/img/filtering/conditions-2.png
  static/img/filtering/filter.png
  static/img/filtering/filtered-total.png
  static/img/filtering/highlight-2.png
  static/img/filtering/highlight.png
  static/img/filtering/modify-saved.png
  static/img/filtering/multiple-filters.png
  static/img/filtering/save-filter.png
  static/img/filtering/select-saved-1.png
  static/img/filtering/select-saved-2.png
  static/img/filtering/selected-total.png
  static/img/filtering/set-filter-name.png
  static/img/filtering/year-1.png
  static/img/filtering/year-2.png
Labels: :white_check_mark: Approved

#634 update payees page
  docs/transactions/payees.md
  static/img/payees/BudgetOptionButton.png
  static/img/payees/ManagingPayees.png
  static/img/payees/MergePayeesOption.png
  static/img/payees/MergePayeesSearch.png
  static/img/payees/Payees.png
  static/img/payees/PayeesMerged.png
  static/img/payees/PayeesSelected.png
Labels: :white_check_mark: Approved

#631 Documenting percentage adjustments feature for actual PR #4257
  .github/actions/spelling/expect.txt
  docs/experimental/goal-templates.md
Labels: :white_check_mark: Approved

#624 Add Priotecs MoneyControl importer reference
  .github/actions/spelling/expect.txt
  docs/community-repos.md
Labels: :white_check_mark: Approved

#644 [WIP] Small grammar correction to filters docs page
  docs/transactions/filters.md
Labels: :construction: WIP

#642 Correct Rule link syntax, url and drop-down menu item name on schedul…
  docs/schedules.md
Labels: :mag: Ready for review

#641 Grammar correction to starting-fresh.md page
  docs/getting-started/starting-fresh.md
Labels: :mag: Ready for review

#639 Small doc correction to local.md install instructions
  docs/install/local.md
Labels: :white_check_mark: Approved

#640 Two small corrections to config docs page
  docs/config/index.md
Labels: :mag: Ready for review

#646 Update sync server config information
  docs/actual-server-repo-move.md
  docs/config/https.md
  docs/config/index.md
  docs/experimental/oauth-auth.md
Labels: :white_check_mark: Approved

#643 Add SimpleFIN where GoCardless mentioned in Accounts docs
  docs/accounts/index.md
Labels: :white_check_mark: Approved

#649 add lelemm to maintainer list
  docs/contributing/index.md
Labels: :white_check_mark: Approved
