Repository actualbudget/docs, pull requests merged in 2025-03, with the labels that each got.

#651 🔖 (25.3.0)
  .github/actions/spelling/expect.txt
  blog/2025-03-01-release-25-3-0.md
  docs/releases.md
Labels: :white_check_mark: Approved

#652 Update github container reference to new repo
  docs/actual-server-repo-move.md
  docs/install/docker.md
Labels: :white_check_mark: Approved

#625 Note on fixing nYNAB duplicates after import
  docs/migration/nynab.md
Labels: :white_check_mark: Approved, Merge at Software Release

#653 Add docs on data to move
  docs/actual-server-repo-move.md
Labels: :white_check_mark: Approved

#655 Update missing start server command
  docs/install/local.md
Labels: :white_check_mark: Approved

#656 🔖 (25.3.1)
  blog/2025-03-03-release-25-3-1.md
  docs/releases.md
Labels: :white_check_mark: Approved

#648 add gcp cloud run install option
  docs/install/index.md
Labels: :white_check_mark: Approved

#650 Added environment variables to OpenID page
  .github/actions/spelling/expect.txt
  docs/experimental/oauth-auth.md
Labels: :white_check_mark: Approved

#660 Add missing doc about env vars.
  docs/config/index.md
Labels: :mag: Ready for review

#661 Update docs with new instructions for workspace reference in server
  docs/actual-server-repo-move.md
  docs/contributing/project-details/index.md
  docs/contributing/releasing.md
  docs/contributing/windows.md
  docs/install/local.md
Labels: :mag: Ready for review

#664 Adding git bash as a prereq for Windows & renaming local install to Build from source
  docs-sidebar.js
  docs/actual-server-repo-move.md
  docs/config/https.md
  docs/config/index.md
  docs/getting-started/roadmap-for-new-users.md
  docs/install/build-from-source.md
  docs/install/index.md
  src/pages/download.md
Labels: :white_check_mark: Approved

#665 Update documentation to include new yarn generate:release-notes script
  docs/contributing/index.md
Labels: :white_check_mark: Approved

#667 Pluggy docs
  .github/actions/spelling/expect.txt
  docs-sidebar.js
  docs/advanced/bank-sync.md
  docs/advanced/bank-sync/simplefin.md
  docs/experimental/pluggyai.md
  static/img/connecting-your-bank/pluggy-console-01.png
  static/img/connecting-your-bank/pluggy-console-02.png
  static/img/connecting-your-bank/pluggy-console-03.png
  static/img/connecting-your-bank/pluggy-setup-add-account.png
  static/img/connecting-your-bank/pluggy-setup-modal-link-account.png
  static/img/connecting-your-bank/pluggy-setup-modal-setup.png
  static/img/connecting-your-bank/pluggy-setup-modal.png
Labels: :white_check_mark: Approved

#670 Added callback url to openid page
  docs/experimental/oauth-auth.md
Labels: :mag: Ready for review

#669 Updating repo move instructions to include bash requirement
  docs/actual-server-repo-move.md
Labels: :white_check_mark: Approved

#671 Added pluggy warning trial
  docs/experimental/pluggyai.md
  static/img/connecting-your-bank/pluggy-trial-warning.png
Labels: :mag: Ready for review
