Repository actualbudget/docs, pull requests merged in 2025-04, with the labels that each got.

#673 🔖 (25.4.0)
  .github/actions/spelling/expect.txt
  blog/2025-04-03-release-25-4-0.md
  docs/releases.md
Labels: :white_check_mark: Approved

#674 call out electron sync server embedding in 25.4.0 release
  blog/2025-04-03-release-25-4-0.md
  docs/releases.md
Labels: :white_check_mark: Approved

#676 fix download links
  src/pages/download.md
Labels: :white_check_mark: Approved

#677 Added instructions for disabling automatic rule creation
  docs/budgeting/rules/index.md
Labels: :white_check_mark: Approved

#678 added documentation for merging transactions
  docs-sidebar.js
  docs/transactions/merging.md
  static/img/merging_transactions.png
Labels: :white_check_mark: Approved

#683 [WIP] Update community-repos.md to add actual-auto-sync
  docs/community-repos.md
Labels: :construction: WIP

#668 Update Reports Documentation
  docs/reports/index.md
  static/img/reports/calendar-card.png
  static/img/reports/cash-flow.png
  static/img/reports/net-worth.png
  static/img/reports/reports-dashboard.png
  static/img/reports/spending-analysis.png
  static/img/reports/summary-card.png
  static/img/reports/text-widget.png
Labels: :white_check_mark: Approved

#654 Update schedules.md
  docs/schedules.md
Labels: :mag: Ready for review

#662 Update https.md to include config.json creation through terminal
  docs/config/https.md
Labels: :mag: Ready for review

#684 [WIP] Update community-repos.md to correct tool name from "Actual Budget Auth Sync" to "Actual Budget Auto Sync".
  docs/community-repos.md
Labels: :construction: WIP

#685 Openid config changed with convict config
  docs/experimental/oauth-auth.md
Labels: :mag: Ready for review

#675 [WIP] Removed GPS informations from matt-fidd.jpeg
  static/img/authors/matt-fidd.jpeg
Labels: :construction: WIP

#666 [WIP] free tier clarification in gocardless.md
  docs/advanced/bank-sync/gocardless.md
Labels: :construction: WIP

#672 [WIP] Update actual-server-repo-move.md
  docs/actual-server-repo-move.md
Labels: :construction: WIP

#682 [WIP] downloads: intel and apple silicon mac labels [#681]
  src/pages/download.md
Labels: :construction: WIP

#686 Update index.md
  docs/contributing/index.md
Labels: :mag: Ready for review

#679 [WIP] Update pluggyai.md - Adding missing required setting step
  docs/experimental/pluggyai.md
Labels: :construction: WIP
