Repository actualbudget/docs, pull requests merged in 2025-06, with the labels that each got.

#710 add an alternative Synology guide
  docs/install/index.md
Labels: :white_check_mark: approved

#713 Syncs transactions from banks like Akahu and Up to Actual Budget
  .github/actions/spelling/allow/keywords.txt
  docs/community-repos.md
Labels: :white_check_mark: approved

#715 🔖 (25.6.0)
  .github/actions/spelling/expect.txt
  blog/2025-06-03-release-25-6-0.md
  docs/releases.md
Labels: :mag: ready for review

#716 Desktop server docs
  docs-sidebar.js
  docs/install/desktop-app.md
  static/img/install/change-server.png
  static/img/install/configure-server.png
Labels: :white_check_mark: approved, merge at release

#712 move multi user docs since its been released
  docs-sidebar.js
  docs/config/multi-user.md
  docs/config/oauth-auth.md
Labels: :white_check_mark: approved, merge at release

#720 Add triaging issues guidelines to contributing documentation
  .github/actions/spelling/expect.txt
  docs-sidebar.js
  docs/contributing/leadership/triaging-issues.md
Labels: :white_check_mark: approved, AI generated

#721 Add sponsored Cursor subscription details for core contributors
  docs/contributing/leadership/new-core-contributors-guide.md
Labels: :white_check_mark: approved, AI generated

#719 [WIP] ActualTap documentation
  docs/community-repos.md
Labels: :construction: WIP

#709 :pencil: (proposal for spending community funds)
  blog/2025-06-08-spending-community-funds.md
  docs/contributing/index.md
Labels: :mag: ready for review

#714 Update contributing/project-details
  docs/contributing/project-details/index.md
Labels: :white_check_mark: approved

#725 apple container docs
  docs-sidebar.js
  docs/install/apple-container.md
Labels: :white_check_mark: approved

#730 Add Cursor IDE documentation
  .github/actions/spelling/expect.txt
  docs-sidebar.js
  docs/contributing/leadership/cursor-ide.md
  docs/contributing/leadership/new-core-contributors-guide.md
Labels: :white_check_mark: approved

#736 [WIP] Fixing a typo in the documentation
  docs/index.md
Labels: :construction: WIP

#737 Added Warning callout as this was missing
  docs/contributing/writing-docs.md
Labels: :white_check_mark: approved
