Repository actualbudget/docs, pull requests merged in 2025-08, with the labels that each got.

#763 🔖 (25.8.0)
  .github/actions/spelling/expect.txt
  blog/2025-08-01-release-25-8-0.md
  docs/releases.md
Labels: :white_check_mark: approved

#756 Add Tags documentation
  docs-sidebar.js
  docs/transactions/tags.md
  static/img/tags/filter.png
  static/img/tags/input-result.png
  static/img/tags/input.png
  static/img/tags/manage.png
Labels: :white_check_mark: approved, merge at release

#758 fix: mention ACTUAL_DATA_DIR is now dataDar in config
  docs/actual-server-repo-move.md
  docs/config/https.md
  docs/config/index.md
  docs/config/oauth-auth.md
  docs/troubleshooting/server.md
Labels: :white_check_mark: approved

#766 [WIP] Adding bank: fixed instructions order
  docs/advanced/bank-sync/gocardless.md
Labels: :construction: WIP

#768 Upgrade docusaurus
  .github/actions/spelling/advice.md
  blog/2024-09-03-release-24.9.0.md
  docs-sidebar.js
  docs/budgeting/multi-currency.md
  docs/contributing/preview-builds.md
  docs/contributing/writing-docs.md
  docs/experimental/goal-templates.md
  docs/experimental/rule-templating.md
  docs/install/fly.md
  docs/releases.md
  docs/settings/index.md
  docs/tour/settings.md
  docusaurus.config.js
  package.json
  src/css/custom.css
  src/pages/download.md
  src/remark/mentions.js
  src/remark/rewrite-images.js
  yarn.lock
Labels: :mag: ready for review

#761 Another starting fresh method
  docs/advanced/restart.md
  docs/getting-started/starting-fresh.md
  static/img/accounts/account-delete-all-transactions.png
Labels: :white_check_mark: approved

#774 Download page is now centered.
  src/pages/download.md
Labels: :white_check_mark: approved

#771 Change search plugin to a more accurate one
  README.md
  docs/contributing/writing-docs.md
  docusaurus.config.js
  package.json
  src/hooks/useThemeSync.js
  src/theme/Layout/index.js
  yarn.lock
Labels: :white_check_mark: approved

#784 [WIP] Update restore.md
  docs/backup-restore/restore.md
Labels: :construction: WIP
